services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=inv-api-db'
      - 'POSTGRES_PASSWORD=inv-api-secret'
      - 'POSTGRES_USER=inv-api-user'
    ports:
      - '5432'
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/inv-api-db
      - SPRING_DATASOURCE_USERNAME=inv-api-user
      - SPRING_DATASOURCE_PASSWORD=inv-api-secret